### ISSUE TITLE
(SI - PB9) listdonor

### ISSUE THREAD

**Issue by Hosxen** [SI-RPL-2022/SI4309_G_DONORDARAH#10]
memasukan daftar kegiatan donor darah

**Comment by Hosxen** [comment]
memasukan dafatar isi kegiatan

**Comment by Hosxen** [comment]
![gambar](https://user-images.githubusercontent.com/92033276/173993237-e48fb6a4-854f-43d7-abab-9d503a927f6b.png)

**Comment by Hosxen** [comment]
memasukan beberapa dafrtar isi sebagai identtisa

**Comment by sahrabifa** [comment]
![image](https://user-images.githubusercontent.com/92034596/176068018-ef6d7073-ab90-44ed-98db-aa50318b1d56.png)
