### ISSUE TITLE
(SI - PB13) contact

### ISSUE THREAD

**Issue by Hosxen** [SI-RPL-2022/SI4309_G_DONORDARAH#16]
Melakukan tambahan fitur kontak\

**Comment by Hosxen** [comment]
![gambar](https://user-images.githubusercontent.com/92033276/174661541-46b711bd-9f5d-431b-8f6a-755df0fbb3fd.png)

**Comment by sahrabifa** [comment]
![image](https://user-images.githubusercontent.com/92034596/176067452-96c854b1-26c4-4727-996e-0641de04b29b.png)
![image](https://user-images.githubusercontent.com/92034596/176067502-38ccddb5-4b17-4ae1-9b57-80e31ee9210f.png)
